version: "3.9"

services:
  api:
    build: .
    container_name: assets-mgmt-api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./web
    container_name: assets-mgmt-web
    command: ["npm", "run", "build"]
    volumes:
      - web-dist:/app/dist

  nginx:
    image: nginx:alpine
    container_name: assets-mgmt-nginx
    ports:
      - "80:80"
    volumes:
      - web-dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web

  db:
    image: postgres:15
    container_name: assets-mgmt-db
    restart: always
    environment:
      POSTGRES_DB: assets_mgmt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      PGDATABASE: assets_mgmt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  web-dist:
